<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../assets/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../assets/css/about_us.css">
    <link rel="shortcut icon" type="image/jpg" href="../assets/img/fav16.png"/>
    <title>Курси програмування</title>
</head>
<body>
<header>
    <?php include_once PUB . "components/navigation.phtml" ?>
</header>

<section>
    <div class="about">
        <div class="container">
            <div class="about_us">
                <div class="text_info"><h1>ХТО МИ</h1></div>
                <p>Design & Development laboratory – навчальний центр для дітей та дорослих в області IT
                    (сучасних технологій).</p>
                <br>
                <p>IT-сфера – одна з найперспективніших галузей майбутнього. Програмісти, веб-розробники та графічні
                    дизайнери – професії можливостей, затребуваної та цікавої роботи, високих заробітних плат. А з
                    розвитком сучасних технологій їх актуальність та популярність лише зростатиме. І ми як ніхто це
                    розуміємо.</p>
                <br>
                <p>Команда DDL працює на ринку освітніх послуг вже понад 2 роки. Наші студенти – успішно засвоїли
                    та продовжують удосконалювати знання та навички у процесі навчання.
                    Наші учні – спеціалісти-початківці, неодноразові переможці олімпіад та майбутні професіонали
                    IT-сфери.</p>
                <br>
                <p>Студенти DDL – люди, які поєднали особисті захоплення із навчанням. Створення власних програм,
                    професійна обробка графічних зображень, розробка власного сайту чи ігор — все це та багато іншого
                    наші учні навчаються робити самостійно.</p>
                <br>
                <p>Будь – який курс нашої школи починається з пояснення основ. А гнучка модульна система дозволяє обрати
                    курс за особистими вподобаннями та навичками.</p>
                <br>
                <p>Майбутнє починається вже сьогодні. Розпочніть перші сміливі кроки до захоплюючої, перспективної та
                    високооплачуваної професії разом з DDL. Ми переконані — майбутнє за IT!</p>
            </div>
        </div>

        <div class="icon">
            <i class="fa fa-facebook" aria-hidden="true"></i>
            <i class="fa fa-instagram" aria-hidden="true"></i>
        </div>
    </div>
</section>

<script src="assets/js/vue.js"></script>
<script src="components/navigation.js"></script>

</body>
</html>