<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../assets/css/admin.css">
    <link rel="stylesheet" type="text/css" href="../assets/font-awesome-4.7.0/css/font-awesome.min.css">
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="logo_admin">
        <a href="/"><img src="../assets/img/logo_header_main_page.png" alt="bg"></a>
    </div>
    <div class="admin-content">
        <div class="link">
            <p>Имя пользователя или email</p>
            <form><input type="name"></form>
            <p>Пароль</p>
            <form><input type="e-mail "><a href="#"><i class="fa fa-eye" aria-hidden="true"></i></a></form>

            <div class="checkbox">
                <input type="checkbox">
                <a href="#">Запомнить меня</a>
                <a href="#">Войти</a>
            </div>
        </div>
    </div>
    <div class="link a">
        <p><a href="#">Забыли пароль?</a>
        </p>
        <p>
            <a href="#">← Назад к сайту «D&D laboratory»</a>
        </p>
    </div>
</div>
</body>
</html>