<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../assets/css/contact.css">
    <link rel="shortcut icon" type="image/jpg" href="../assets/img/fav16.png"/>
    <link rel="stylesheet" type="text/css" href="../assets/font-awesome-4.7.0/css/font-awesome.min.css">
    <title>Курси програмування</title>
</head>
<body>
<header id="header_main_page">
    <?php include_once PUB . "components/navigation.phtml" ?>
    <div class="wrapper"><span class="text">ГРАЙ, МАЛЮЙ, ПРОГРАМУЙ!</span><span class="pointer">|</span></div>
</header>
<?php include_once PUB . "components/contacts.phtml" ?>
<script src="../assets/js/vue.js"></script>
<script src="../components/navigation.js"></script>
<script src="../components/contacts.js"></script>
<script src="../components/text-animate.js"></script>


</body>
</html>
