<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../assets/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../assets/css/dream.css">
    <link rel="stylesheet" type="text/css" href="../assets/css/common.css">
    <link rel="shortcut icon" type="image/jpg" href="../assets/img/fav16.png"/>
    <title>Курси програмування</title>
</head>
<body>
<header>
    <?php include_once PUB . "components/navigation.phtml" ?>
</header>

<section>
    <div class="container">
        <div class="dream">
            <div class="text_info"><h1>ДРІМ ТІМ</h1></div>
            <div class="photo">
                <img src="assets/img/j_0.png">
                <h3>ЄВГЕН РИБЧЕНКО</h3>
                <p>Викладач курсів «Вчи граючи» та «Вчи кодуючи»</p>
                <span>Спеціаліст з програмування.</span>
            </div>

            <div class="photo">
                <img src="assets/img/kolya.png">
                <h3>МИКОЛА ТУПІЦИН</h3>
                <p>Викладач курсів «Вчи малюючи» та «Вчи граючи»</p>
                <span>Спеціаліст з програмування та інженерії.</span>
            </div>

            <div class="photo">
                <img src="assets/img/i_0.png">
                <h3>ІРИНА КАРАЗЕЙ</h3>
                <p>Викладач курсів «Вчи граючи» та «Вчи знаючи»</p>
                <span>Спеціаліст з веб-дизайну.</span>
            </div>

            <div class="photo">
                <img src="assets/img/d_0.png">
                <h3>ДМИТРО ІВАНОВ</h3>
                <p>Викладач курсів «Вчи знаючи» та «Вчи кодуючи»</p>
                <span>Спеціаліст з програмування.</span>
            </div>

            <div class="photo">
                <img src="assets/img/A_1.png">
                <h3>АНДРІЙ ЛЯШКО</h3>
                <p>Викладач курсів «Вчи малюючи» та «Вчи знаючи»</p>
                <span>Спеціаліст з програмування та інженерії.</span>
            </div>
        </div>
    </div>
</section>
<script src="assets/js/vue.js"></script>
<script src="components/navigation.js"></script>

</body>
</html>