<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../assets/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../assets/css/common.css">
    <link rel="stylesheet" type="text/css" href="../assets/css/error.css">
    <link rel="shortcut icon" type="image/jpg" href="../assets/img/fav16.png"/>
    <title>Курси програмування</title>
</head>
<body>
<header id="error">
    <div class="container">
        <div class="entrance">
            <i class="fa fa-lock" aria-hidden="true"></i>
            Войти на сайт
        </div>
        <div class="icon-error">
            <i class="fa fa-id-card-o" aria-hidden="true"></i>
            <i class="fa fa-id-card-o" aria-hidden="true"></i>
            <i class="fa fa-id-card-o" aria-hidden="true"></i>
            <i class="fa fa-id-card-o" aria-hidden="true"></i>
        </div>
    </div>
</header>
<div class="border">
    <div class="container">
        <div class="logo_error">
            <img src="assets/img/logo_header_main_page.png">
        </div>
        <div class="icon-error2">
            <i class="fa fa-id-card-o" aria-hidden="true"></i>
        </div>
    </div>

        <div class="center">
            ФАЙЛ НЕ НАЙДЕН
        </div>
</div>
<div class="flex">
        <div class="border_error border1"></div>
        <div class="border_error">
                <span><a href="#"> Домой</a><a href="#"> / Ошибка 404</a>
                </span></div>
        <div class="border_error border1"></div>
</div>
<div class="container">
    <div class="text-error">
        ОЙ
    </div>
    <div class="error">
        <p class="error404">404</p>

    <div class="nothing_found">
        Ничего не найдено
        <p>
            Мы не можем найти то, что Вы ищете. Возможно, поиск по одной из ссылок ниже может быть полезен.</p>
    </div>
        <p class="home">
            <a href="index.phtml">
                ВЕРНУТЬСЯ К ДОМАШНЕЙ СТРАНИЦЕ
            </a>
        </p>
    </div>
    <div class="form">
        <div class="form-left">
            Поиск в архивах
            <form>
            <select>
                <option>Октябрь 2020</option>
                <option>Сентябрь 2020</option>
                <option>Август 2020</option>
            </select>
            </form>
        </div>
        <div class="form-right">
            Поиск по сайту
            <form><input type="name"></form>
        </div>
    </div>
</div>


<script src="assets/js/main.js"></script>
</body>
</html>