<section id="contact">
    <div class="container"><h2>КОНТАКТИ</h2>
        <div class="block3"><i class="fa fa-map-marker"
                               aria-hidden="true"></i><span>просп. В. Маяковського 26</span></div>
        <div class="block3"><i class="fa fa-mobile" aria-hidden="true"></i><span>тел: 067 390 00 88</span></div>
        <div class="block3"><i class="fa fa-address-card-o"
                               aria-hidden="true"></i>
            <span>ddlaboratory.pro@gmail.com</span>
        </div>
        <div class="map-image-container" v-on:mouseover="showMap=true">
            <transition name="map">
                <div class="map-image" v-if="!showMap"></div>
            </transition>

            <iframe v-if="showMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2537.417288158241!2d30.60704631573352
            !3d50.50780207948338!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4d0555afe578d%3A0x79c891ec81
            1243f6!2z0L_RgNC-0YHQvy4g0JLQu9Cw0LTQuNC80LjRgNCwINCc0LDRj9C60L7QstGB0LrQvtCz0L4sIDI2LCDQmtC40LXQsiwgMDI
            wMDA!5e0!3m2!1sru!2sua!4v1580473793500!5m2!1sru!2sua"
                    width="100%" height="250" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        </div>

    </div>

</section>